networks:
  - name: private
    type: dynamic
    cloud_properties:
      vswitch_id: ((vswitch_id))
      security_group_id: ((security_group_id))
  - name: vip
    type: vip

vm_types:
  - name: default
    cloud_properties: &default_cloud_properties
      instance_type: ecs.sn2.medium
      availability_zone: ((zone))
  - name: slb_registration_pool
    cloud_properties:
      <<: *default_cloud_properties
      slbs: [((slb))]
  - name: spot_instance_pool
    cloud_properties:
      <<: *default_cloud_properties
      instance_type: ecs.sn1ne.large
      spot_strategy: "SpotWithPriceLimit"
      spot_price_limit: 0.10 # 10x the normal bid price

compilation:
  reuse_compilation_vms: true
  workers: 1
  network: private
  cloud_properties:
    instance_type: ecs.sn2.medium
    availability_zone: ((zone))
