---
platform: linux

image_resource:
  type: docker-image
  source: {repository: oucwangyue/alicloud-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: environment
  - name: stemcell
  - name: heavy-stemcell
  - name: bosh-cli
  - name: director-state
  - name: jq-blob
  - name: libffi-blob
  - name: libpqxx-blob
  - name: pip-blob
  - name: python-blob
  - name: python-setup-tools-blob
  - name: pycrypto-blob
  - name: core-blob
  - name: slb-blob
  - name: aliyun-cli

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x bosh-cpi-src/ci/tasks/run-e2e.sh
    bash bosh-cpi-src/ci/tasks/run-e2e.sh

params:
  BOSH_DEBUG_LEVEL: info
  ALICLOUD_ACCESS_KEY_ID:      ""
  ALICLOUD_SECRET_ACCESS_KEY:      ""